"""create user and blog table migrations

Revision ID: 9e8c52302d4b
Revises: f3d9b20200a9
Create Date: 2025-03-04 11:24:18.217938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8c52302d4b'
down_revision: Union[str, None] = 'f3d9b20200a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
